### ISSUE TITLE
Unable to Add New Subregions if Image already has Subregions Segmented

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/ihc-image-analysis#26]
When I go to generate more training data for an image and select, say bronchiole, if some training data has already been generated for that image, I am unable to add new subregions to that image.

**Comment by whitews** [comment]
I agree this would be nice. It requires some work in the drw-poly directive to allow enabling/disabling of individual polygons. I submitted an issue in the [drw-poly repo here](https://github.com/whitews/drw-poly/issues/1).
