### ISSUE TITLE
Unable to Delete Segments and/or Nodes in Segments

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/ihc-image-analysis#27]
Using Chrome on Mac, the right-click to delete a node or segment does not work in deleting the desired entity. When I click on a node to delete, it will go away for a second, but then quickly reappear. Let me know if additional detail is needed.

**Comment by whitews** [comment]
Hey Ben, I just tried Chrome on a Mac mini and cannot replicate the issue. I wonder if it is because you have a track pad?

**Comment by benneely** [comment]
Correct - I'm using a trackpad. No access to a mouse over here so can't confirm whether or not that is the only culprit.

**Comment by whitews** [comment]
Hmm, I wonder if there are going to be cross-platform mouse issues if we should consider a keypress event to delete stuff then?

**Comment by whitews** [comment]
Ben, I borrowed a Mac laptop and you can right-click using the bottom right-hand corner of the trackpad (the same way it works on my Dell). Using Ctrl + click is not an actual right-click event. There may be a setting for this option that you may or may not have enabled. But, you can try this and see if it works for you.

**Comment by benneely** [comment]
Looks like I wasn't doing a proper right hand click. I was doing a ctrl+click. For future reference, proper click logic here: https://www.cnet.com/how-to/five-ways-to-right-click-on-a-mac-trackpad/.
