### ISSUE TITLE
lungmap_client.lungmap_utils broken

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/ihc-image-analysis#33]
The `SPARQL` queries that `lungmap_client.lungmap_utils` rely on (i.e. `lungmap_client.lungmap_sparql_queries` no longer work. This appears to be due to the underlying Lungmap infrastructure changing. Still this affects everything from running the `preload_analytics_models` script to adding new models (e.g. `anatlytics.models.Experiment`) as these modules rely on lungmap_utils.

**Comment by whitews** [comment]
SPARQL queries updated along with the supporting code that uses them
