### ISSUE TITLE
Toggling between 'train' & 'classify', then back to 'train' enables drawing even with no classification selected

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/ihc-image-analysis#37]
When a user first gets to the imageset details page, selects an image, selects a subregion, they are ready to begin segmenting. However, drw-poly is not in focus at this point. Users have to click on classify and then back on train in order to begin creating training data.

**Comment by whitews** [comment]
Actually this bug is slightly different. Toggling from 'train' mode to 'classify' and back to 'train' without a sub-region classification specified should not enable the user to draw sub-regions, but it currently does.
