### ISSUE TITLE
insert text into information modal

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/ihc-image-analysis#39]
make bullet points. when text gets too large link to markdown

**Comment by benneely** [comment]
As part of this issue, I'd like to conditionally populate this modal. The `How to Create Training Data` should be limited to only when `mode == 'train'`, if `mode == classify` then maybe we can put the information modal next to the classify button and populate a different modal?

**Comment by whitews** [comment]
Or alternatively put both instructions in the same modal. I'm not sure it is intuitive that clicking the same information button at different times would provide different information.

**Comment by benneely** [comment]
The trouble is with how that modal is implemented. It is launched as a function (from img_set_detail.html). That function hard codes the title: `How to Create Training Data`. If we use that modal for both, we need to find a way to differentiate instructions for `Train` vs. `Classify`. If we could embed html, I could see this happening, but right now, all we have is a list of strings displayed. Should this be done a different way?

**Comment by whitews** [comment]
Then change the title to something more generic?
