### ISSUE TITLE
Add link to INSTRUCTIONS.md on information modal

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/ihc-image-analysis#47]
on image set detail page, add link to instructions.md on information modal for users who want more in-depth information.

**Comment by benneely** [comment]
@whitews - for this issue, I can see two implementations. (1) Simply put the URL to the `UI_INSTRUCTIONS.md` file in the list - this will be displayed as text and users will need to copy paste the URL. (2) Create a new function (or modified the existing) function `open_modal` in `main_controller.js` so that we parameterize the `template_url`. This would allow us to use HTML syntax in our modal's and use href to get to this file. 

What are your thoughts?

**Comment by whitews** [comment]
Let's add a new dedicated template for this case and hard code all the content there, formatted however we want. This is fine and probably more appropriate because nothing in that modal is dynamic anyway.
