### ISSUE TITLE
Classify Functionality: Sort Results

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/ihc-image-analysis#51]
We should return the highest probability anatomy first, to make it easy for users.

**Comment by whitews** [comment]
Agreed, and this would be easier to do if we made a dedicated modal template for this as well. We could then create a more organized list of results objects with like properties and then use Angular's orderBy in the partial. Do you want to take a stab at this one?

**Comment by benneely** [comment]
Yes! Will take a stab.
