### ISSUE TITLE
Model Pipeline Returning Equal Probability When Equal Training Data in Classes

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/ihc-image-analysis#56]
There is a bug somewhere in the gridsearch / svd pipeline that returns equal probability when the number of training images is equal in the classes. To replicate simply train a model that has equal number of training images in each class. To mitigate, simply add one more training image to any class.

**Comment by benneely** [comment]
Here is our pipeline:
```
clf = GridSearchCV(SVC(probability=True), svc_params, cv=4)
pipe = Pipeline([
        ('scaler', StandardScaler()),
        ('feature_selection', SelectFdr()),
        ('classification', clf)
    ])
```
The offending code is `GridSearchCV`. Since we are going to generally have very small training sets, what do you think about just going with defaults for SVC?

**Comment by whitews** [comment]
Ben, have you tried an alternative that avoids the problem and gives good results?

**Comment by cliburn** [comment]
In particular, can you try leave-one-out? Perhaps with a switch to 3-fold when number of examples is large (say > 10)
