### ISSUE TITLE
Programmatic Authentication

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/ihc-image-analysis#62]
Add and endpoint that allows programmatic clients to authenticate.

**Comment by benneely** [comment]
After discussing with @whitews, decided that clients should use a `requests.Session` to first capture the `csrftoken`. Next, users should hit the `login` endpoint and pass in credentials along with the `csrfmiddlewaretoken`, like so:

```
login_data = {'username': username, 'password': password, 'csrfmiddlewaretoken': csrftoken}
session.post(url_login, data=login_data, verify=False, headers={'Referer': url_login})
```
From there, the users session should be utilized to gain programmatic access to our backend.

**Comment by whitews** [comment]
Exactly, and just to complete the picture of how this works...after a successful login POST, the session instance will receive a cookie containing the session ID and one with the csrf token. The server also has these values and as long as they match for each request, all is good. On each successful request, the server updates the session's expiration time. If the user remains idle, making no requests, after that time, the session is no longer valid.
