### ISSUE TITLE
Limit /api/lungmapexperiments

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/ihc-image-analysis#9]
We discussed limiting the experiments returned from `/api/lungmapexperiments` to only include experiments with certain images. Feel free to alter this issue, but I believe we may only want it to include `Immunofluorescence-Confocal` images. Maybe we should just make it versitile and allow the endpoint to take parameters that will allow certain experiments to be returned. For example, maybe also `Annotated` or `Histological stain`.

**Comment by whitews** [comment]
I altered the SPARQL query in c80ab577f4b69c0498da0ee53d1c0ba411fa4a05 to limit the experiments to just the fluoro ones. We could add some logic to allow selected others but I'm not sure we need to as we have no concrete plans as of yet to expand the analysis pipeline to those.
